---
- name: Configuration du serveur web MediTrack
  hosts: web
  become: yes

  tasks:

    - name: Mettre à jour les paquets
      dnf:
        name: "*"
        state: latest

    # =========================
    # SUPPRIMER APACHE SI PRÉSENT
    # =========================

    - name: Stop Apache if running
      service:
        name: httpd
        state: stopped
      ignore_errors: yes

    - name: Remove Apache
      dnf:
        name: httpd
        state: absent

    # =========================
    # NGINX
    # =========================

    - name: Installer Nginx
      dnf:
        name: nginx
        state: present

    - name: Démarrer et activer Nginx
      service:
        name: nginx
        state: started
        enabled: true

    - name: Déployer page MediTrack
      copy:
        src: files/index.html
        dest: /usr/share/nginx/html/index.html
        owner: nginx
        group: nginx
        mode: '0644'

    # =========================
    # FIREWALL
    # =========================

    - name: Installer firewalld
      dnf:
        name: firewalld
        state: present

    - name: Démarrer firewalld
      service:
        name: firewalld
        state: started
        enabled: true

    - name: Autoriser HTTP
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

    # =========================
    # POSTGRESQL CLIENT + DNS
    # =========================

    - name: Installer PostgreSQL client
      dnf:
        name: postgresql15
        state: present

    - name: Installer outils DNS (nslookup, dig)
      dnf:
        name: bind-utils
        state: present